SRC_DIR = "video/nu_card_test.mp4"
CROP_THRS_DIR = "output/crop_thrs_img/"
TESSERACT_OUTPUT_DIR = "output/tesseract_output/"
NU_CARD_DATA = "output/nu_card_data/"
RAW_FRAME_WITH_RECT = "output/raw_frame_with_rect/"